# Site settings
title: Lucas da Silva
email: lucas@lucas.ninja
description: > # this means to ignore newlines until "baseurl:"
  Web Developer, accessibility and #webperf addict!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucas.ninja" # the base hostname & protocol for your site
twitter_username: _agtlucas
github_username:  agtlucas

excerpt_separator: <!-- more -->

exclude: ['node_modules', 'package.json', 'gulpfile.js', 'src', '.DS_Store', '.sass-cache', 'README.md', 'npm-debug.log']

sass:
    sass_dir: _sass
    style: :compressed

paginate: 10
paginate_path: "blog/page-:num"

include: ['.gitignore', 'CNAME']

# Build settings
markdown: kramdown
